### ISSUE TITLE
[FEATURE] 추천 기능 구현

### ISSUE THREAD

**Issue by mjjeon2645** [mjjeon2645/pre-onboarding-10th-3-9-in-js#3]
### 🤸 Describe the required feature
- 사용자가 input에 타이핑을 하면 일치하는 아이템들이 dropdown에 보여질 수 있도록 InputTodo에 추천 기능 구현하기

### 🏊 Todo

- [ ] 상황 별 인풋창 종류 구현
  - [ ] default
  - [ ] hovered
  - [ ] clicked
  - [ ] typing
  - [ ] searching
  - [ ] typed 1
  - [ ] typed 2
- [ ] 검색 시 드랍다운 및 드랍다운 내역에서 검색어가 색상으로 활성화
- [ ] 검색 시 드랍다운 내 호버 및 클릭 상황
  - [ ] hover
  - [ ] click
- [ ] 검색 시 드랍다운 내용이 길 때, 스크롤 하단에 표시 아이콘
- [ ] 검색 내용이 로딩횔 때 무한 로딩 스피너
- [ ] Input에 500ms 디바운스 적용
- [ ] 드롭다운에서 아이템 하나 선택 시 input의 value는 초기화 되고 아이템이 리스트에 추가되도록 구현
